import Head from "next/head";
import React from "react";

export default function HomePage(): JSX.Element {
  return (
    <Head>
      <title>flowbite-nextjs-starter</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>
  );
}
